name: build & deploy
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Use Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: generate icons
        run: npm run generate:icons

      - name: version
        run: echo "CLERKENT_VERSION=$(npm run version --silent)" >> $GITHUB_ENV
        id: version

      - name: build
        run: |
          npm run build
          mv extension/chrome.zip extension/${{ env.CLERKENT_VERSION }}-chrome.zip
          mv extension/firefox.xpi extension/${{ env.CLERKENT_VERSION }}-firefox.xpi
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          generate_release_notes: true
          files: |
            extension/${{ env.CLERKENT_VERSION }}-chrome.zip
            extension/${{ env.CLERKENT_VERSION }}-firefox.xpi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: lacuna-technologies/clerkent

      - uses: trmcnvn/firefox-addon@v1
        with:
          uuid: '{68470d9e-14a9-4697-a19b-413d6773c788}'
          xpi: extension/${{ env.CLERKENT_VERSION }}-firefox.xpi
          manifest: extension/firefox//manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}

      # - uses: mnao305/chrome-extension-upload@1.1.1
      #   with:
      #     file-path: extension/${{ env.CLERKENT_VERSION }}-chrome.zip
      #     extension-id: ogjefnociaddjemkkajgmfpmhmpokmhj
      #     client-id: ${{ secrets.CHROME_CLIENT_ID }}
      #     client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
      #     refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
