name: build & test
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install dependencies
        run: pnpm install
      - name: lint
        run: pnpm run lint
      - name: generate icons
        run: pnpm run generate:icons
      - name: run tests
        run: pnpm run test:ci
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: run FOSSA scan
        uses: fossa-contrib/fossa-action@v1
        with:
          fossa-api-key: ${{ secrets.FOSSA_API_KEY }}